In [1]:
[1, 2, 3] * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [2]:
[1, 2, 3] * [4, 5, 6]

TypeError: can't multiply sequence by non-int of type 'list'

# Numerical Python (Numpy)

In [8]:
import numpy as np

In [9]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [10]:
a * 3

array([3, 6, 9])

# Math Functions

In [11]:
np.sum(a)

6

In [12]:
np.mean(a)

2.0

In [13]:
np.std(a)

0.816496580927726

In [14]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

# arange, linspace, logspace

In [15]:
np.arange(0, 5, 2)

array([0, 2, 4])

In [16]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [17]:
np.logspace(-3, 3, 7)

array([1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03])

# Random

In [27]:
np.random.rand(3, 2)

array([[0.09552559, 0.63541965],
       [0.91741184, 0.23805313],
       [0.10214196, 0.87127344]])

# Controlled Randomness

In [28]:
state = np.random.RandomState(42)
state.rand(3)

array([0.37454012, 0.95071431, 0.73199394])